# Generated by Django 5.1.7 on 2025-05-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('ethnic', models.CharField(max_length=20)),
                ('religion', models.CharField(max_length=30)),
                ('hometown', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('title_detail', models.CharField(blank=True, max_length=100)),
                ('title_granted_at', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('quota_code', models.CharField(max_length=200)),
                ('salary_coefficient', models.FloatField()),
                ('salary_coefficient_granted_at', models.DateField()),
                ('recruited_at', models.DateField()),
                ('years_of_experience', models.IntegerField()),
                ('exp_academic', models.JSONField()),
                ('exp_language', models.TextField(blank=True)),
                ('exp_computer', models.TextField(blank=True)),
                ('exp_work', models.JSONField()),
                ('researches', models.JSONField()),
                ('published_works', models.JSONField()),
                ('recommender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecturers.lecturer')),
                ('subjects', models.ManyToManyField(to='lecturers.subject')),
            ],
        ),
    ]
