# Generated by Django 5.1.7 on 2025-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='exp_work',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='published_works',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='researches',
            field=models.JSONField(blank=True),
        ),
    ]
