# Generated by Django 5.1.7 on 2025-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_link', models.URLField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('valid_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.CharField(blank=True, max_length=100, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
