# Generated by Django 5.1.7 on 2025-05-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('can_view_document', 'Can view document'), ('can_add_document', 'Can add document'), ('can_change_document', 'Can change document'), ('can_delete_document', 'Can delete document'))},
        ),
    ]
